### Variables 
@apiurlNext = http://localhost:8085
@tokenERPNEXT = <ERPNEXT_API_KEY>:<ERPNEXT_API_SECRET>
@apiongsys = https://www.ongsys.com.br/app/index.php/api/v2

@tokenongsys = <ONGSYS_USERNAME>:<ONGSYS_PASSWORD>

@ONGSYS_USER = <ONGSYS_USERNAME>
@ONGSYS_PASS = <ONGSYS_PASSWORD>

### 🔐 Login no ERPNext (gera o cookie "sid")
### GET - Buscar Stock Entry específico
GET {{apiurlNext}}/api/resource/Stock%20Entry/MAT-STE-2025-00020?fields=%5B%22*%22%5D
Authorization: token {{tokenERPNEXT}}
Accept: application/json
Content-Type: application/json


##  pegue todos os pedidos ongys 
### GET - Buscar todos os pedidos na Ongsys
GET {{apiongsys}}/pedidos?pageNumber=1
Authorization: Basic <ONGSYS_BASIC_AUTH_TOKEN>
Accept: application/json
Content-Type: application/json


##0 criando idpedido
### POST - Criar campo personalizado "idpedido" em Stock Entry no ERPNext
POST {{apiurlNext}}/api/resource/Custom%20Field
Authorization: token {{tokenERPNEXT}}
Content-Type: application/json

{
  "dt": "Stock Entry",
  "label": "idpedido",
  "fieldname": "idpedido",
  "fieldtype": "Text",
  "insert_after": "stock_entry_type"
}


### PUT - Atualizar Stock Entry com o campo personalizado "idpedido"
GET {{apiurlNext}}/api/resource/Custom%20Field?filters=[["dt","=","Stock Entry"]]&fields=["name","label","fieldname","fieldtype"]
Authorization: token {{tokenERPNEXT}}
Accept: application/json


### teste 
POST {{apiurlNext}}/api/method/frappe.client.get_list
Authorization: token {{tokenERPNEXT}}
Accept: application/json
Content-Type: application/json

{
  "doctype": "Stock Entry Detail",
  "filters": { "parent": "MAT-STE-2025-00020" },
  "fields": ["*"],
  "limit_page_length": 1000
}